### ISSUE TITLE
New firmware for R210 (SMR210GLU0AQC6)

### ISSUE THREAD

**Issue by LogicBypass** [KieronQuinn/Gear360_OSS#2]
Just downloaded new firmware for R210 (SMR210GLU0AQC6)
link:
https://drive.google.com/file/d/161W5dT8w3didFc3khIrzvU5-mhQV29-c/view?usp=sharing
Can you compile it or can leave instructions how to do it?

**Comment by KieronQuinn** [comment]
As far as I'm aware nobody has ever successfully compiled a firmware from the open source files. Do you have a firmware bin file?

**Comment by p-gh** [comment]
I just purchased a new Gear 360 R210 to replace a broken one. I've trying to use the micro SD method to update the firmware with bin and updater.sh in the root directory of the SD but nothing happens.  

Am I missing something?

**Comment by KieronQuinn** [comment]
See this comment:

https://github.com/KieronQuinn/Gear360_OSS/issues/1#issuecomment-813468180

**Comment by p-gh** [comment]
Thank you! The new Gear 360 now has the latest firmware!

**Comment by ge0rg** [comment]
Hi,

I'm a bit late to the game, but I'm trying to collect all info that is there for Samsung's NX (and also Gear360) Linux cameras. I've started documenting the `bin` firmware file format in https://github.com/ge0rg/samsung-nx-hacks/wiki/SLP-Firmware-Format but it looks like Samsung never released a `fw_generator` for DRIMe5 devices. Do you know of one or maybe additional resources to check? I've downloaded all three OSS zips for Gear360 2016 and 2017 and there was nothing of relevance :( Samsung OSS inquiries keep telling me that I'm asking for too old hardware and they can't help me.

**Comment by KieronQuinn** [comment]
I haven't seen a generator, no
